services:
  - type: web
    name: cruise-leimer-island
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DB_PATH
        value: /data/cruise.db
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
